### ISSUE TITLE
auc:FloorsBelowGrade Max at 1

### ISSUE THREAD

**Issue by corymosiman12** [BuildingSync/BuildingSync-gem#48]
Trying to define more than 1 `auc:FloorsBelowGrade` results in the following:

```
/Users/cmosiman/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/bundler/gems/openstudio-model-articulation-gem-2adec90118c0/lib/openstudio/model_articulation/os_lib_model_generation_bricr.rb:652:in `block in create_bar': undefined method `[]' for nil:NilClass (NoMethodError)
        from /Users/cmosiman/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/bundler/gems/openstudio-model-articulation-gem-2adec90118c0/lib/openstudio/model_articulation/os_lib_model_generation_bricr.rb:650:in `each'
        from /Users/cmosiman/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/bundler/gems/openstudio-model-articulation-gem-2adec90118c0/lib/openstudio/model_articulation/os_lib_model_generation_bricr.rb:650:in `each_with_index'
        from /Users/cmosiman/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/bundler/gems/openstudio-model-articulation-gem-2adec90118c0/lib/openstudio/model_articulation/os_lib_model_generation_bricr.rb:650:in `create_bar'
        from /Users/cmosiman/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/bundler/gems/BuildingSync-gem-50edf2060dd5/lib/buildingsync/model_articulation/building.rb:763:in `generate_baseline_osm'
        from /Users/cmosiman/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/bundler/gems/BuildingSync-gem-50edf2060dd5/lib/buildingsync/model_articulation/site.rb:260:in `generate_baseline_osm'
        from /Users/cmosiman/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/bundler/gems/BuildingSync-gem-50edf2060dd5/lib/buildingsync/model_articulation/facility.rb:123:in `generate_baseline_osm'
        from /Users/cmosiman/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/bundler/gems/BuildingSync-gem-50edf2060dd5/lib/buildingsync/makers/model_maker_level_zero.rb:68:in `generate_baseline'
        from /Users/cmosiman/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/bundler/gems/BuildingSync-gem-50edf2060dd5/lib/buildingsync/translator.rb:115:in `write_osm'

```

**Comment by TMaile** [comment]
@corymosiman12 do you have a test file for this?

**Comment by corymosiman12** [comment]
Hey Tobias - see [here](https://github.com/corymosiman12/test_suite/blob/master/tests/Level_100/inputs/L100_Instance1.xml)

**Comment by corymosiman12** [comment]
Hey @TMaile can you help remind me if this ever got resolved, and where exactly?  Looking to close out some issues if possible.

**Comment by TMaile** [comment]
Hi @corymosiman12, this issue is still open, we did not get around to fix it.

**Comment by corymosiman12** [comment]
Ok - thanks for the clarification.

**Comment by TMaile** [comment]
I added a proper error message now that it is easier to understand when this issue occurs. 
https://github.com/BuildingSync/BuildingSync-gem/commit/9d3a543e11ef2581d318f56b9b42c8e61ba48ba0

**Comment by TMaile** [comment]
@corymosiman12 the updated L100_Audit.xml contains two stories below ground, can you update that?

**Comment by TMaile** [comment]
L100_audit file is updated and we issue a proper error message, so this is done
