### ISSUE TITLE
Unsuccessful Baseline Simulation - Errors in gather_results function

### ISSUE THREAD

**Issue by corymosiman12** [BuildingSync/BuildingSync-gem#97]
Branch: DA_Update
Commit: https://github.com/BuildingSync/BuildingSync-gem/commit/f570704546d5784c38504292620914f1071af632

### Setup
Created a simple function:
```ruby

def baseline_creation(file_path, output_path)
  FileUtils.mkdir_p(output_path) if !File.exist?(output_path)
  translator = BuildingSync::Translator.new(file_path, output_path)
  translator.write_osm
  translator.write_osws
  translator.run_osm(epw_name = '')
  translator.run_osws
  translator.gather_results(FILES_DIR)
end

path_to_file = '~/my/file/Example.xml'
output_path = '~/my/file/outputs'

baseline_creation(path_to_file, output_path)
```
The sizing run seems ok and the Baseline path gets created as expected:
![image](https://user-images.githubusercontent.com/28991233/98977214-5dd12e00-24e6-11eb-96cf-6dd6ace94ba4.png)

### Errors
in.log
```
[BuildingSync.Translator.run_osm] <1> Could not add reporting measure to osw
[BuildingSync.WorkflowMaker.gather_results] <1> The following error occurred undefined method `[]' for nil:NilClass while processing results in /Users/cmosiman/Github/BSync-OS-Sandbox
[BuildingSync.WorkflowMaker.gather_results] <1> The following error occurred undefined local variable or method `osw_dir' for #<BuildingSync::WorkflowMaker:0x00007ffb0bc92f80> while processing results in /Users/cmosiman/Github/BSync-OS-Sandbox
```

run.log
```
[10:36:42.689865 ERROR] Found error in state 'initialization' with message ["Weather file '../../../weather/' specified but cannot be found:/Users/cmosiman/Github//BSync-OS-Sandbox/.bundle/install/ruby/2.5.0/gems/openstudio-extension-0.2.5/.bundle/install/ruby/2.5.0/gems/openstudio-workflow-2.0.1/lib/openstudio/workflow/jobs/run_initialization.rb:192:in `perform'\n/Users/cmosiman/Github/BSync-OS-Sandbox/.bundle/install/ruby/2.5.0/gems/openstudio-extension-0.2.5/.bundle/install/ruby/2.5.0/gems/openstudio-workflow-2.0.1/lib/openstudio/workflow/run.rb:292:in `step'\n/Users/cmosiman/Github/BSync-OS-Sandbox/.bundle/install/ruby/2.5.0/gems/openstudio-extension-0.2.5/.bundle/install/ruby/2.5.0/gems/openstudio-workflow-2.0.1/lib/openstudio/workflow/run.rb:234:in `run'\n:/openstudio_cli.rb:960:in `execute'\n:/openstudio_cli.rb:750:in `execute'\n:/openstudio_cli.rb:1744:in `<main>'\neval:174:in `eval'\neval:174:in `require_embedded_absolute'\neval:160:in `block in require_embedded'\neval:154:in `each'\neval:154:in `require_embedded'\neval:113:in `require'\neval:3:in `<main>'"]}
[10:36:48.799300 ERROR] Found error in state 'initialization' with message ["Weather file '../../../weather/' specified but cannot be found:/Users/cmosiman/Github/BSync-OS-Sandbox/.bundle/install/ruby/2.5.0/gems/openstudio-workflow-2.0.1/lib/openstudio/workflow/jobs/run_initialization.rb:192:in `perform'\n/Users/cmosiman/Github/BSync-OS-Sandbox/.bundle/install/ruby/2.5.0/gems/openstudio-workflow-2.0.1/lib/openstudio/workflow/run.rb:292:in `step'\n/Users/cmosiman/Github/BSync-OS-Sandbox/.bundle/install/ruby/2.5.0/gems/openstudio-workflow-2.0.1/lib/openstudio/workflow/run.rb:234:in `run'\n:/openstudio_cli.rb:960:in `execute'\n:/openstudio_cli.rb:750:in `execute'\n:/openstudio_cli.rb:1744:in `<main>'\neval:174:in `eval'\neval:174:in `require_embedded_absolute'\neval:160:in `block in require_embedded'\neval:154:in `each'\neval:154:in `require_embedded'\neval:113:in `require'\neval:3:in `<main>'"]}
```

**Comment by corymosiman12** [comment]
Fixed.
